# Generated by Django 3.2.16 on 2022-12-08 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'publication_date', 'ordering': ['-publication_date'], 'permissions': (('can_view_all', 'Can view all entries'), ('can_change_status', 'Can change status'), ('can_change_author', 'Can change author(s)')), 'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='publication_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="Used to build the entry's URL.", verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='zinnia.category', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='entries', to='zinnia.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content_template',
            field=models.CharField(choices=[('zinnia/_entry_detail.html', 'Default template')], default='zinnia/_entry_detail.html', help_text="Template used to display the entry's content.", max_length=250, verbose_name='content template'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='detail_template',
            field=models.CharField(choices=[('entry_detail.html', 'Default template')], default='entry_detail.html', help_text="Template used to display the entry's detail page.", max_length=250, verbose_name='detail template'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_zinnia_entry_related_+', to='zinnia.Entry', verbose_name='related entries'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(help_text="Used to build the entry's URL.", max_length=255, unique_for_date='publication_date', verbose_name='slug'),
        ),
        migrations.AlterIndexTogether(
            name='entry',
            index_together={('slug', 'publication_date'), ('status', 'publication_date', 'start_publication', 'end_publication')},
        ),
    ]
